# Generated by Django 4.2.2 on 2023-07-30 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestedprogram',
            name='stage',
            field=models.CharField(choices=[('Interested', 'Interested'), ('Applied', 'Applied'), ('Admitted', 'Admitted'), ('Joined', 'Joined')], default='Interested', max_length=20),
        ),
    ]
