# Generated by Django 4.2.2 on 2023-08-02 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_university_domain_alter_university_city_and_more'),
        ('users', '0004_alter_interestedprogram_stage'),
        ('chatroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='universities.university'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='users',
            field=models.ManyToManyField(related_name='channels', to='users.userprofile'),
        ),
    ]
