# Generated by Django 4.2.2 on 2023-08-09 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_university_domain_alter_university_city_and_more'),
        ('chatroom', '0002_channel_university_alter_channel_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='universities.university'),
        ),
    ]
